//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatabeWedding.CatWeb.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Shared {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shared() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WatabeWedding.CatWeb.Resources.Shared", typeof(Shared).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key value is duplicated..
        /// </summary>
        internal static string ERR_DUP_KEY {
            get {
                return ResourceManager.GetString("ERR_DUP_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data was not found..
        /// </summary>
        internal static string ERR_NOTFOUND {
            get {
                return ResourceManager.GetString("ERR_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete this record because it is already used..
        /// </summary>
        internal static string ERR_USEDKEY_DELETE {
            get {
                return ResourceManager.GetString("ERR_USEDKEY_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カナ(1).
        /// </summary>
        internal static string LBL_ADDR_KANA1 {
            get {
                return ResourceManager.GetString("LBL_ADDR_KANA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カナ(2).
        /// </summary>
        internal static string LBL_ADDR_KANA2 {
            get {
                return ResourceManager.GetString("LBL_ADDR_KANA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カナ(3).
        /// </summary>
        internal static string LBL_ADDR_KANA3 {
            get {
                return ResourceManager.GetString("LBL_ADDR_KANA3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 漢字(1).
        /// </summary>
        internal static string LBL_ADDR_KANJI1 {
            get {
                return ResourceManager.GetString("LBL_ADDR_KANJI1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 漢字(2).
        /// </summary>
        internal static string LBL_ADDR_KANJI2 {
            get {
                return ResourceManager.GetString("LBL_ADDR_KANJI2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 漢字(3).
        /// </summary>
        internal static string LBL_ADDR_KANJI3 {
            get {
                return ResourceManager.GetString("LBL_ADDR_KANJI3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 住所.
        /// </summary>
        internal static string LBL_ADDRESS {
            get {
                return ResourceManager.GetString("LBL_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent.
        /// </summary>
        internal static string LBL_AGENT_CD {
            get {
                return ResourceManager.GetString("LBL_AGENT_CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Tour Code.
        /// </summary>
        internal static string LBL_AGENT_TOUR_CD {
            get {
                return ResourceManager.GetString("LBL_AGENT_TOUR_CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        internal static string LBL_ANY {
            get {
                return ResourceManager.GetString("LBL_ANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Code.
        /// </summary>
        internal static string LBL_AREA_CD {
            get {
                return ResourceManager.GetString("LBL_AREA_CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arr Date.
        /// </summary>
        internal static string LBL_ARR_DATE {
            get {
                return ResourceManager.GetString("LBL_ARR_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrangement Info.
        /// </summary>
        internal static string LBL_ARR_INFO {
            get {
                return ResourceManager.GetString("LBL_ARR_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arr Time.
        /// </summary>
        internal static string LBL_ARR_TIME {
            get {
                return ResourceManager.GetString("LBL_ARR_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant/Dispatch.
        /// </summary>
        internal static string LBL_ASSISTANT_DISPATCH {
            get {
                return ResourceManager.GetString("LBL_ASSISTANT_DISPATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string LBL_ATT_COUNT {
            get {
                return ResourceManager.GetString("LBL_ATT_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string LBL_ATT_NAME {
            get {
                return ResourceManager.GetString("LBL_ATT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendants&apos; Hotel.
        /// </summary>
        internal static string LBL_ATTENDANTS_HOTEL {
            get {
                return ResourceManager.GetString("LBL_ATTENDANTS_HOTEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bride CustType.
        /// </summary>
        internal static string LBL_B_CUSTTYPE {
            get {
                return ResourceManager.GetString("LBL_B_CUSTTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bride First Name.
        /// </summary>
        internal static string LBL_B_FIRST {
            get {
                return ResourceManager.GetString("LBL_B_FIRST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bride Last Name.
        /// </summary>
        internal static string LBL_B_LAST {
            get {
                return ResourceManager.GetString("LBL_B_LAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance Due.
        /// </summary>
        internal static string LBL_BALANCE_DUE {
            get {
                return ResourceManager.GetString("LBL_BALANCE_DUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BFg Date.
        /// </summary>
        internal static string LBL_BF_DATE {
            get {
                return ResourceManager.GetString("LBL_BF_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bfg Time.
        /// </summary>
        internal static string LBL_BF_TIME {
            get {
                return ResourceManager.GetString("LBL_BF_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking.
        /// </summary>
        internal static string LBL_BOOKING {
            get {
                return ResourceManager.GetString("LBL_BOOKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新婦.
        /// </summary>
        internal static string LBL_BRIDE {
            get {
                return ResourceManager.GetString("LBL_BRIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bride Name.
        /// </summary>
        internal static string LBL_BRIDE_NAME {
            get {
                return ResourceManager.GetString("LBL_BRIDE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bride.
        /// </summary>
        internal static string LBL_BRIDE2 {
            get {
                return ResourceManager.GetString("LBL_BRIDE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer#.
        /// </summary>
        internal static string LBL_C_NUM {
            get {
                return ResourceManager.GetString("LBL_C_NUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cust#.
        /// </summary>
        internal static string LBL_C_NUM_SHORT {
            get {
                return ResourceManager.GetString("LBL_C_NUM_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cfmd.
        /// </summary>
        internal static string LBL_CFMD {
            get {
                return ResourceManager.GetString("LBL_CFMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge.
        /// </summary>
        internal static string LBL_CHARGE {
            get {
                return ResourceManager.GetString("LBL_CHARGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        internal static string LBL_CHECK_IN {
            get {
                return ResourceManager.GetString("LBL_CHECK_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out.
        /// </summary>
        internal static string LBL_CHECK_OUT {
            get {
                return ResourceManager.GetString("LBL_CHECK_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Church.
        /// </summary>
        internal static string LBL_CHURCH_CD {
            get {
                return ResourceManager.GetString("LBL_CHURCH_CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference#.
        /// </summary>
        internal static string LBL_CLAIM_NUM {
            get {
                return ResourceManager.GetString("LBL_CLAIM_NUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concierge.
        /// </summary>
        internal static string LBL_CONCIERGE {
            get {
                return ResourceManager.GetString("LBL_CONCIERGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回数.
        /// </summary>
        internal static string LBL_COUNT {
            get {
                return ResourceManager.GetString("LBL_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couple Attd.
        /// </summary>
        internal static string LBL_COUPLE_ATTD {
            get {
                return ResourceManager.GetString("LBL_COUPLE_ATTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Collect.
        /// </summary>
        internal static string LBL_CUSTOMER_COLLECT {
            get {
                return ResourceManager.GetString("LBL_CUSTOMER_COLLECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Kind.
        /// </summary>
        internal static string LBL_CUSTOMER_KIND {
            get {
                return ResourceManager.GetString("LBL_CUSTOMER_KIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Movement.
        /// </summary>
        internal static string LBL_CUSTOMER_MOVEMENT {
            get {
                return ResourceManager.GetString("LBL_CUSTOMER_MOVEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string LBL_CUSTOMER_MOVEMENT_DATE {
            get {
                return ResourceManager.GetString("LBL_CUSTOMER_MOVEMENT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        internal static string LBL_CUSTOMER_MOVEMENT_DELIVERY {
            get {
                return ResourceManager.GetString("LBL_CUSTOMER_MOVEMENT_DELIVERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string LBL_CUSTOMER_MOVEMENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("LBL_CUSTOMER_MOVEMENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goods Pick.
        /// </summary>
        internal static string LBL_CUSTOMER_MOVEMENT_GOODS_PICK {
            get {
                return ResourceManager.GetString("LBL_CUSTOMER_MOVEMENT_GOODS_PICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        internal static string LBL_CUSTOMER_MOVEMENT_IDLE {
            get {
                return ResourceManager.GetString("LBL_CUSTOMER_MOVEMENT_IDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string LBL_CUSTOMER_MOVEMENT_IN_DONE {
            get {
                return ResourceManager.GetString("LBL_CUSTOMER_MOVEMENT_IN_DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        internal static string LBL_CUSTOMER_MOVEMENT_IN_PROGRESS {
            get {
                return ResourceManager.GetString("LBL_CUSTOMER_MOVEMENT_IN_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outside Service.
        /// </summary>
        internal static string LBL_CUSTOMER_MOVEMENT_OUTSIDE_SERVICE {
            get {
                return ResourceManager.GetString("LBL_CUSTOMER_MOVEMENT_OUTSIDE_SERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string LBL_CUSTOMER_MOVEMENT_TIME {
            get {
                return ResourceManager.GetString("LBL_CUSTOMER_MOVEMENT_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string LBL_CUSTOMER_MOVEMENT_TYPE {
            get {
                return ResourceManager.GetString("LBL_CUSTOMER_MOVEMENT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Type.
        /// </summary>
        internal static string LBL_CUSTTYPE {
            get {
                return ResourceManager.GetString("LBL_CUSTTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CXL.
        /// </summary>
        internal static string LBL_CXL {
            get {
                return ResourceManager.GetString("LBL_CXL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CXL Charge Info.
        /// </summary>
        internal static string LBL_CXL_CHARGE_INFO {
            get {
                return ResourceManager.GetString("LBL_CXL_CHARGE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CXLD.
        /// </summary>
        internal static string LBL_CXLD {
            get {
                return ResourceManager.GetString("LBL_CXLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string LBL_DATE {
            get {
                return ResourceManager.GetString("LBL_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date / By.
        /// </summary>
        internal static string LBL_DATE_BY {
            get {
                return ResourceManager.GetString("LBL_DATE_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date(Day).
        /// </summary>
        internal static string LBL_DATE_DAY {
            get {
                return ResourceManager.GetString("LBL_DATE_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date From.
        /// </summary>
        internal static string LBL_DATE_FROM {
            get {
                return ResourceManager.GetString("LBL_DATE_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date To.
        /// </summary>
        internal static string LBL_DATE_TO {
            get {
                return ResourceManager.GetString("LBL_DATE_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dep.
        /// </summary>
        internal static string LBL_DEP {
            get {
                return ResourceManager.GetString("LBL_DEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dep Time.
        /// </summary>
        internal static string LBL_DEP_TIME {
            get {
                return ResourceManager.GetString("LBL_DEP_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 個人情報開示の同意.
        /// </summary>
        internal static string LBL_DISCLOSURE {
            get {
                return ResourceManager.GetString("LBL_DISCLOSURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 送信しない.
        /// </summary>
        internal static string LBL_DO_NOT_SEND {
            get {
                return ResourceManager.GetString("LBL_DO_NOT_SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dst.
        /// </summary>
        internal static string LBL_DST {
            get {
                return ResourceManager.GetString("LBL_DST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        internal static string LBL_DUE_DATE {
            get {
                return ResourceManager.GetString("LBL_DUE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string LBL_DUE_DESCRIPTION {
            get {
                return ResourceManager.GetString("LBL_DUE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        internal static string LBL_EMAIL {
            get {
                return ResourceManager.GetString("LBL_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entertainer.
        /// </summary>
        internal static string LBL_ENTERTAINER {
            get {
                return ResourceManager.GetString("LBL_ENTERTAINER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIN.
        /// </summary>
        internal static string LBL_FIN {
            get {
                return ResourceManager.GetString("LBL_FIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final.
        /// </summary>
        internal static string LBL_FINAL {
            get {
                return ResourceManager.GetString("LBL_FINAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名.
        /// </summary>
        internal static string LBL_FIRST_NAME {
            get {
                return ResourceManager.GetString("LBL_FIRST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fitting &amp; Briefing Information.
        /// </summary>
        internal static string LBL_FITTING_BRIEFING_INFOMATION {
            get {
                return ResourceManager.GetString("LBL_FITTING_BRIEFING_INFOMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight.
        /// </summary>
        internal static string LBL_FLIGHT {
            get {
                return ResourceManager.GetString("LBL_FLIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string LBL_FRIGHT_ID {
            get {
                return ResourceManager.GetString("LBL_FRIGHT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string LBL_FROM {
            get {
                return ResourceManager.GetString("LBL_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ftg Date.
        /// </summary>
        internal static string LBL_FT_DATE {
            get {
                return ResourceManager.GetString("LBL_FT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ftg Time.
        /// </summary>
        internal static string LBL_FT_TIME {
            get {
                return ResourceManager.GetString("LBL_FT_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groom CustType.
        /// </summary>
        internal static string LBL_G_CUSTTYPE {
            get {
                return ResourceManager.GetString("LBL_G_CUSTTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groom First Name.
        /// </summary>
        internal static string LBL_G_FIRST {
            get {
                return ResourceManager.GetString("LBL_G_FIRST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groom Last Name.
        /// </summary>
        internal static string LBL_G_LAST {
            get {
                return ResourceManager.GetString("LBL_G_LAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新郎.
        /// </summary>
        internal static string LBL_GROOM {
            get {
                return ResourceManager.GetString("LBL_GROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groom &amp; Bride Hotel.
        /// </summary>
        internal static string LBL_GROOM_BRIDE_HOTEL {
            get {
                return ResourceManager.GetString("LBL_GROOM_BRIDE_HOTEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groom Name.
        /// </summary>
        internal static string LBL_GROOM_NAME {
            get {
                return ResourceManager.GetString("LBL_GROOM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groom.
        /// </summary>
        internal static string LBL_GROOM2 {
            get {
                return ResourceManager.GetString("LBL_GROOM2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Attd.
        /// </summary>
        internal static string LBL_GUEST_ATTD {
            get {
                return ResourceManager.GetString("LBL_GUEST_ATTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History Note.
        /// </summary>
        internal static string LBL_HISTORY_NOTE {
            get {
                return ResourceManager.GetString("LBL_HISTORY_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 電話 (ご自宅).
        /// </summary>
        internal static string LBL_HOME_TEL {
            get {
                return ResourceManager.GetString("LBL_HOME_TEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel.
        /// </summary>
        internal static string LBL_HOTEL_CD {
            get {
                return ResourceManager.GetString("LBL_HOTEL_CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTLp/u.
        /// </summary>
        internal static string LBL_HTL_PICK {
            get {
                return ResourceManager.GetString("LBL_HTL_PICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incharge.
        /// </summary>
        internal static string LBL_INCHARGE {
            get {
                return ResourceManager.GetString("LBL_INCHARGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Cd.
        /// </summary>
        internal static string LBL_ITEM_CD {
            get {
                return ResourceManager.GetString("LBL_ITEM_CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Type.
        /// </summary>
        internal static string LBL_ITEM_TYPE {
            get {
                return ResourceManager.GetString("LBL_ITEM_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 郵便番号.
        /// </summary>
        internal static string LBL_JPN_ZIP {
            get {
                return ResourceManager.GetString("LBL_JPN_ZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カナ.
        /// </summary>
        internal static string LBL_KANA {
            get {
                return ResourceManager.GetString("LBL_KANA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 漢字.
        /// </summary>
        internal static string LBL_KANJI {
            get {
                return ResourceManager.GetString("LBL_KANJI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land Customer Note.
        /// </summary>
        internal static string LBL_LAND_CUSTOMER_NOTE {
            get {
                return ResourceManager.GetString("LBL_LAND_CUSTOMER_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string LBL_LANG_NAME {
            get {
                return ResourceManager.GetString("LBL_LANG_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 氏.
        /// </summary>
        internal static string LBL_LAST_NAME {
            get {
                return ResourceManager.GetString("LBL_LAST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limo Driver.
        /// </summary>
        internal static string LBL_LIMO_DRIVER {
            get {
                return ResourceManager.GetString("LBL_LIMO_DRIVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minister.
        /// </summary>
        internal static string LBL_MINISTER {
            get {
                return ResourceManager.GetString("LBL_MINISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musician.
        /// </summary>
        internal static string LBL_MUSICIAN {
            get {
                return ResourceManager.GetString("LBL_MUSICIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MYページ情報.
        /// </summary>
        internal static string LBL_MYPAGE_INFO {
            get {
                return ResourceManager.GetString("LBL_MYPAGE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MYページ再送.
        /// </summary>
        internal static string LBL_MYPAGE_RE_SENDING {
            get {
                return ResourceManager.GetString("LBL_MYPAGE_RE_SENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新居住所.
        /// </summary>
        internal static string LBL_NEW_ADDRESS {
            get {
                return ResourceManager.GetString("LBL_NEW_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最新回答日.
        /// </summary>
        internal static string LBL_NEW_ANSWERDATE {
            get {
                return ResourceManager.GetString("LBL_NEW_ANSWERDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最新送信日.
        /// </summary>
        internal static string LBL_NEW_SENDDATE {
            get {
                return ResourceManager.GetString("LBL_NEW_SENDDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NG.
        /// </summary>
        internal static string LBL_NG {
            get {
                return ResourceManager.GetString("LBL_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Cfmd Only.
        /// </summary>
        internal static string LBL_NOT_CFMD {
            get {
                return ResourceManager.GetString("LBL_NOT_CFMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not CXL Only.
        /// </summary>
        internal static string LBL_NOT_CXL {
            get {
                return ResourceManager.GetString("LBL_NOT_CXL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT Finalize.
        /// </summary>
        internal static string LBL_NOT_FINAL {
            get {
                return ResourceManager.GetString("LBL_NOT_FINAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Invoiced.
        /// </summary>
        internal static string LBL_NOT_INVOICED {
            get {
                return ResourceManager.GetString("LBL_NOT_INVOICED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string LBL_NOTE {
            get {
                return ResourceManager.GetString("LBL_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinator.
        /// </summary>
        internal static string LBL_NOTE_COORDINATOR {
            get {
                return ResourceManager.GetString("LBL_NOTE_COORDINATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string LBL_NOTE_GENERAL {
            get {
                return ResourceManager.GetString("LBL_NOTE_GENERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iWink Spot.
        /// </summary>
        internal static string LBL_NOTE_IWINK_SPOT {
            get {
                return ResourceManager.GetString("LBL_NOTE_IWINK_SPOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note to Agent.
        /// </summary>
        internal static string LBL_NOTE_TO_AGENT {
            get {
                return ResourceManager.GetString("LBL_NOTE_TO_AGENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note to Vendor.
        /// </summary>
        internal static string LBL_NOTE_TO_VENDOR {
            get {
                return ResourceManager.GetString("LBL_NOTE_TO_VENDOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WINK Agent.
        /// </summary>
        internal static string LBL_NOTE_WINK_AGENT {
            get {
                return ResourceManager.GetString("LBL_NOTE_WINK_AGENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string LBL_OFFICE_VISIT_AREA {
            get {
                return ResourceManager.GetString("LBL_OFFICE_VISIT_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BF.
        /// </summary>
        internal static string LBL_OFFICE_VISIT_BF {
            get {
                return ResourceManager.GetString("LBL_OFFICE_VISIT_BF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string LBL_OFFICE_VISIT_DATE {
            get {
                return ResourceManager.GetString("LBL_OFFICE_VISIT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FT.
        /// </summary>
        internal static string LBL_OFFICE_VISIT_FT {
            get {
                return ResourceManager.GetString("LBL_OFFICE_VISIT_FT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel.
        /// </summary>
        internal static string LBL_OFFICE_VISIT_HOTEL {
            get {
                return ResourceManager.GetString("LBL_OFFICE_VISIT_HOTEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Visit Info (Fitting etc.).
        /// </summary>
        internal static string LBL_OFFICE_VISIT_INFO {
            get {
                return ResourceManager.GetString("LBL_OFFICE_VISIT_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickup.
        /// </summary>
        internal static string LBL_OFFICE_VISIT_PICKUP {
            get {
                return ResourceManager.GetString("LBL_OFFICE_VISIT_PICKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        internal static string LBL_OFFICE_VISIT_PLACE {
            get {
                return ResourceManager.GetString("LBL_OFFICE_VISIT_PLACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        internal static string LBL_OFFICE_VISIT_ROOM {
            get {
                return ResourceManager.GetString("LBL_OFFICE_VISIT_ROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string LBL_OFFICE_VISIT_TIME {
            get {
                return ResourceManager.GetString("LBL_OFFICE_VISIT_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string LBL_OK {
            get {
                return ResourceManager.GetString("LBL_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK With Condition.
        /// </summary>
        internal static string LBL_OK_WITH_CONDITION {
            get {
                return ResourceManager.GetString("LBL_OK_WITH_CONDITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date.
        /// </summary>
        internal static string LBL_ORDER_DATE {
            get {
                return ResourceManager.GetString("LBL_ORDER_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Org.
        /// </summary>
        internal static string LBL_ORG {
            get {
                return ResourceManager.GetString("LBL_ORG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PackageName.
        /// </summary>
        internal static string LBL_PACKAGE_NAME {
            get {
                return ResourceManager.GetString("LBL_PACKAGE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Staff.
        /// </summary>
        internal static string LBL_PARTY_STAFF {
            get {
                return ResourceManager.GetString("LBL_PARTY_STAFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photographer.
        /// </summary>
        internal static string LBL_PHOTOGRAPHER {
            get {
                return ResourceManager.GetString("LBL_PHOTOGRAPHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string LBL_PREVIEW {
            get {
                return ResourceManager.GetString("LBL_PREVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アンケート情報.
        /// </summary>
        internal static string LBL_QUESTIONNAIRE_INFO {
            get {
                return ResourceManager.GetString("LBL_QUESTIONNAIRE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アンケート再送.
        /// </summary>
        internal static string LBL_QUESTIONNAIRE_RE_SENDING {
            get {
                return ResourceManager.GetString("LBL_QUESTIONNAIRE_RE_SENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        internal static string LBL_REGION {
            get {
                return ResourceManager.GetString("LBL_REGION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rehearsal.
        /// </summary>
        internal static string LBL_REHEARSAL {
            get {
                return ResourceManager.GetString("LBL_REHEARSAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        internal static string LBL_REQUEST {
            get {
                return ResourceManager.GetString("LBL_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to Default.
        /// </summary>
        internal static string LBL_RESET_TO_DEFAULT {
            get {
                return ResourceManager.GetString("LBL_RESET_TO_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rm.
        /// </summary>
        internal static string LBL_ROOM {
            get {
                return ResourceManager.GetString("LBL_ROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beauty Service.
        /// </summary>
        internal static string LBL_SALESDETAIL_BEAUTYSERVICE {
            get {
                return ResourceManager.GetString("LBL_SALESDETAIL_BEAUTYSERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costume.
        /// </summary>
        internal static string LBL_SALESDETAIL_COSTUME {
            get {
                return ResourceManager.GetString("LBL_SALESDETAIL_COSTUME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GE Tax.
        /// </summary>
        internal static string LBL_SALESDETAIL_TAX {
            get {
                return ResourceManager.GetString("LBL_SALESDETAIL_TAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GE tax Included).
        /// </summary>
        internal static string LBL_SALESDETAIL_TAX_INCLUDE {
            get {
                return ResourceManager.GetString("LBL_SALESDETAIL_TAX_INCLUDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Total.
        /// </summary>
        internal static string LBL_SALESDETAIL_TOTAL {
            get {
                return ResourceManager.GetString("LBL_SALESDETAIL_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wedding Package &amp; Options.
        /// </summary>
        internal static string LBL_SALESDETAIL_WEDDINGPACKAGE {
            get {
                return ResourceManager.GetString("LBL_SALESDETAIL_WEDDINGPACKAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string LBL_SEARCH {
            get {
                return ResourceManager.GetString("LBL_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sel.
        /// </summary>
        internal static string LBL_SEL {
            get {
                return ResourceManager.GetString("LBL_SEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string LBL_SERVER {
            get {
                return ResourceManager.GetString("LBL_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singer.
        /// </summary>
        internal static string LBL_SINGER {
            get {
                return ResourceManager.GetString("LBL_SINGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by.
        /// </summary>
        internal static string LBL_SORT_BY {
            get {
                return ResourceManager.GetString("LBL_SORT_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string LBL_STATUS {
            get {
                return ResourceManager.GetString("LBL_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Agent.
        /// </summary>
        internal static string LBL_SUB_AGENT_CD {
            get {
                return ResourceManager.GetString("LBL_SUB_AGENT_CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string LBL_TIME {
            get {
                return ResourceManager.GetString("LBL_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string LBL_TO {
            get {
                return ResourceManager.GetString("LBL_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Balance Due.
        /// </summary>
        internal static string LBL_TOTAL_BALANCE_DUE {
            get {
                return ResourceManager.GetString("LBL_TOTAL_BALANCE_DUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Customer Collect.
        /// </summary>
        internal static string LBL_TOTAL_CUSTOMER_COLLECT {
            get {
                return ResourceManager.GetString("LBL_TOTAL_CUSTOMER_COLLECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour By.
        /// </summary>
        internal static string LBL_TOUR_BY {
            get {
                return ResourceManager.GetString("LBL_TOUR_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor.
        /// </summary>
        internal static string LBL_VENDOR_CD {
            get {
                return ResourceManager.GetString("LBL_VENDOR_CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videographer.
        /// </summary>
        internal static string LBL_VIDEOGRAPHER {
            get {
                return ResourceManager.GetString("LBL_VIDEOGRAPHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wedding Customer.
        /// </summary>
        internal static string LBL_WED_CUST {
            get {
                return ResourceManager.GetString("LBL_WED_CUST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wed Cust.
        /// </summary>
        internal static string LBL_WED_CUST_2 {
            get {
                return ResourceManager.GetString("LBL_WED_CUST_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wedding Customer Option.
        /// </summary>
        internal static string LBL_WED_CUST_OPTION {
            get {
                return ResourceManager.GetString("LBL_WED_CUST_OPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wedding Customer Only.
        /// </summary>
        internal static string LBL_WED_CUST_OPTION_CUSTOMER {
            get {
                return ResourceManager.GetString("LBL_WED_CUST_OPTION_CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Wedding Customer Only.
        /// </summary>
        internal static string LBL_WED_CUST_OPTION_NOT_CUSTOMER {
            get {
                return ResourceManager.GetString("LBL_WED_CUST_OPTION_NOT_CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer CXL Option.
        /// </summary>
        internal static string LBL_WED_CXL {
            get {
                return ResourceManager.GetString("LBL_WED_CXL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wcxl.
        /// </summary>
        internal static string LBL_WED_CXL_2 {
            get {
                return ResourceManager.GetString("LBL_WED_CXL_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer CXL Only.
        /// </summary>
        internal static string LBL_WED_CXL_CUSTOMER {
            get {
                return ResourceManager.GetString("LBL_WED_CXL_CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Cutomer CXL Only.
        /// </summary>
        internal static string LBL_WED_CXL_NOT_CUSTOMER {
            get {
                return ResourceManager.GetString("LBL_WED_CXL_NOT_CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string LBL_WED_DATE {
            get {
                return ResourceManager.GetString("LBL_WED_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wed Date.
        /// </summary>
        internal static string LBL_WED_DATE_2 {
            get {
                return ResourceManager.GetString("LBL_WED_DATE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string LBL_WED_TIME {
            get {
                return ResourceManager.GetString("LBL_WED_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wed Time.
        /// </summary>
        internal static string LBL_WED_TIME_2 {
            get {
                return ResourceManager.GetString("LBL_WED_TIME_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wedding.
        /// </summary>
        internal static string LBL_WEDDING {
            get {
                return ResourceManager.GetString("LBL_WEDDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wedding Info.
        /// </summary>
        internal static string LBL_WEDDING_INFO {
            get {
                return ResourceManager.GetString("LBL_WEDDING_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WINK Cusomer Note.
        /// </summary>
        internal static string LBL_WINK_CUSOMER_NOTE {
            get {
                return ResourceManager.GetString("LBL_WINK_CUSOMER_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 電話 (携帯).
        /// </summary>
        internal static string LBL_WORK_TEL {
            get {
                return ResourceManager.GetString("LBL_WORK_TEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WTB Driver.
        /// </summary>
        internal static string LBL_WTB_DRIVER {
            get {
                return ResourceManager.GetString("LBL_WTB_DRIVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a Dedicated Time Block for Special Package....
        /// </summary>
        internal static string MGS_ERROR_JPNBOOK_LOCKED {
            get {
                return ResourceManager.GetString("MGS_ERROR_JPNBOOK_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un-Matched Information!!.
        /// </summary>
        internal static string MGS_ERROR_JPNBOOK_NG {
            get {
                return ResourceManager.GetString("MGS_ERROR_JPNBOOK_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reception Party Room is NOT Available for this time....
        /// </summary>
        internal static string MGS_ERROR_JPNBOOK_NORCP {
            get {
                return ResourceManager.GetString("MGS_ERROR_JPNBOOK_NORCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Check Reception Available time for this Package....
        /// </summary>
        internal static string MGS_ERROR_JPNBOOK_UNMATCH {
            get {
                return ResourceManager.GetString("MGS_ERROR_JPNBOOK_UNMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to proceed?.
        /// </summary>
        internal static string MSG_CONFIRM {
            get {
                return ResourceManager.GetString("MSG_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to change Wedding Customer status?.
        /// </summary>
        internal static string MSG_CONFIRM_CHANGE_WEDDING_CUSTOMER {
            get {
                return ResourceManager.GetString("MSG_CONFIRM_CHANGE_WEDDING_CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booked Party Room Already Exists. Do you want to link this booking to the Booked Room?.
        /// </summary>
        internal static string MSG_CONFIRM_CHECK_WEDORDER_CHANGE_BOOKED {
            get {
                return ResourceManager.GetString("MSG_CONFIRM_CHECK_WEDORDER_CHANGE_BOOKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit Disclosure?.
        /// </summary>
        internal static string MSG_CONFIRM_COMMIT_DISCLOSURE {
            get {
                return ResourceManager.GetString("MSG_CONFIRM_COMMIT_DISCLOSURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit Finalize?.
        /// </summary>
        internal static string MSG_CONFIRM_COMMIT_FINALIZE {
            get {
                return ResourceManager.GetString("MSG_CONFIRM_COMMIT_FINALIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option Package Coupon!! Cannot Delete... \n Do you want to CXL this coupon?.
        /// </summary>
        internal static string MSG_CONFIRM_COUPON_OPTION_COUPON {
            get {
                return ResourceManager.GetString("MSG_CONFIRM_COUPON_OPTION_COUPON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wedding Package Coupon!! Cannot Delete... \n Do you want to CXL this coupon?.
        /// </summary>
        internal static string MSG_CONFIRM_COUPON_PACKAGE_COUPON {
            get {
                return ResourceManager.GetString("MSG_CONFIRM_COUPON_PACKAGE_COUPON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the changes?.
        /// </summary>
        internal static string MSG_CONFIRM_COUPON_SAVE_CHANGE {
            get {
                return ResourceManager.GetString("MSG_CONFIRM_COUPON_SAVE_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to DELETE this record?.
        /// </summary>
        internal static string MSG_CONFIRM_DELETE {
            get {
                return ResourceManager.GetString("MSG_CONFIRM_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Current Booking as BLOCK?.
        /// </summary>
        internal static string MSG_CONFIRM_LEAVE_CURRENT_BOOKING {
            get {
                return ResourceManager.GetString("MSG_CONFIRM_LEAVE_CURRENT_BOOKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string MSG_CONFIRM_SURE {
            get {
                return ResourceManager.GetString("MSG_CONFIRM_SURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo Disclosure?.
        /// </summary>
        internal static string MSG_CONFIRM_UNDO_DISCLOSURE {
            get {
                return ResourceManager.GetString("MSG_CONFIRM_UNDO_DISCLOSURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo Finalize?.
        /// </summary>
        internal static string MSG_CONFIRM_UNDO_FINALIZE {
            get {
                return ResourceManager.GetString("MSG_CONFIRM_UNDO_FINALIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booked Party Room Already Exists. Do you want to link this booking to the Booked Room?.
        /// </summary>
        internal static string MSG_CONFIRM_UPDWEDORDER_ASKROOM {
            get {
                return ResourceManager.GetString("MSG_CONFIRM_UPDWEDORDER_ASKROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already booked by someone else!!  PACKAGE CHANGE???.
        /// </summary>
        internal static string MSG_CONFIRM_UPDWEDORDER_PKGCHG {
            get {
                return ResourceManager.GetString("MSG_CONFIRM_UPDWEDORDER_PKGCHG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input bride&apos;s e-mail address.
        /// </summary>
        internal static string MSG_ERROR_BRIDE_EMAIL {
            get {
                return ResourceManager.GetString("MSG_ERROR_BRIDE_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a Dedicated Time Block for Special Package....
        /// </summary>
        internal static string MSG_ERROR_CHECK_WEDORDER_CHANGE_BLOCK {
            get {
                return ResourceManager.GetString("MSG_ERROR_CHECK_WEDORDER_CHANGE_BLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reception Party Room is NOT Available for this time....
        /// </summary>
        internal static string MSG_ERROR_CHECK_WEDORDER_CHANGE_NOTAVAILABLE {
            get {
                return ResourceManager.GetString("MSG_ERROR_CHECK_WEDORDER_CHANGE_NOTAVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Check Reception Available time for this Package....
        /// </summary>
        internal static string MSG_ERROR_CHECK_WEDORDER_CHANGE_RECEPTION {
            get {
                return ResourceManager.GetString("MSG_ERROR_CHECK_WEDORDER_CHANGE_RECEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somebody else updated this record!!  Recall and Try Again....
        /// </summary>
        internal static string MSG_ERROR_CLAIMNOTE_UPDATE_LOCK {
            get {
                return ResourceManager.GetString("MSG_ERROR_CLAIMNOTE_UPDATE_LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Been Used for RS(DRESS)! CXL RS first....
        /// </summary>
        internal static string MSG_ERROR_COUPON_CXL_USED_DRESS {
            get {
                return ResourceManager.GetString("MSG_ERROR_COUPON_CXL_USED_DRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Been Used for RS(TUX)! CXL RS first....
        /// </summary>
        internal static string MSG_ERROR_COUPON_CXL_USED_TUX {
            get {
                return ResourceManager.GetString("MSG_ERROR_COUPON_CXL_USED_TUX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Item is already INVOICED!!  Please Check.....
        /// </summary>
        internal static string MSG_ERROR_COUPON_INVOICED {
            get {
                return ResourceManager.GetString("MSG_ERROR_COUPON_INVOICED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option Package Coupon!! Cannot Change....
        /// </summary>
        internal static string MSG_ERROR_COUPON_OPTION_COUPON {
            get {
                return ResourceManager.GetString("MSG_ERROR_COUPON_OPTION_COUPON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wedding Package Coupon!! Cannot Change....
        /// </summary>
        internal static string MSG_ERROR_COUPON_PACKAGE_COUPON {
            get {
                return ResourceManager.GetString("MSG_ERROR_COUPON_PACKAGE_COUPON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used Amount Must be 0.00 to Delete Coupon!!.
        /// </summary>
        internal static string MSG_ERROR_COUPON_USED_AMOUNT {
            get {
                return ResourceManager.GetString("MSG_ERROR_COUPON_USED_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used Amount Must be 0.00 to Change Coupon!!.
        /// </summary>
        internal static string MSG_ERROR_COUPON_USED_AMOUNT_CHANGE {
            get {
                return ResourceManager.GetString("MSG_ERROR_COUPON_USED_AMOUNT_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used Amount Must be 0.00 to CXL Coupon!!.
        /// </summary>
        internal static string MSG_ERROR_COUPON_USED_AMOUNT_CXL {
            get {
                return ResourceManager.GetString("MSG_ERROR_COUPON_USED_AMOUNT_CXL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must CXL All Sales Records First!!.
        /// </summary>
        internal static string MSG_ERROR_CXL_1 {
            get {
                return ResourceManager.GetString("MSG_ERROR_CXL_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must CXL RS Order First!!.
        /// </summary>
        internal static string MSG_ERROR_CXL_2 {
            get {
                return ResourceManager.GetString("MSG_ERROR_CXL_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must Process JPN Data (CUST FIN)!!.
        /// </summary>
        internal static string MSG_ERROR_CXL_3 {
            get {
                return ResourceManager.GetString("MSG_ERROR_CXL_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must Process JPN Data (WDNG)!!.
        /// </summary>
        internal static string MSG_ERROR_CXL_4 {
            get {
                return ResourceManager.GetString("MSG_ERROR_CXL_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must Process JPN Data (OPTN)!!.
        /// </summary>
        internal static string MSG_ERROR_CXL_5 {
            get {
                return ResourceManager.GetString("MSG_ERROR_CXL_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must Process JPN Data (MESS)!!.
        /// </summary>
        internal static string MSG_ERROR_CXL_6 {
            get {
                return ResourceManager.GetString("MSG_ERROR_CXL_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must Process WINK Data (WDNG)!!.
        /// </summary>
        internal static string MSG_ERROR_CXL_7 {
            get {
                return ResourceManager.GetString("MSG_ERROR_CXL_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must Process WINK Data (OPTN)!!.
        /// </summary>
        internal static string MSG_ERROR_CXL_8 {
            get {
                return ResourceManager.GetString("MSG_ERROR_CXL_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must Process WINK Data (MESS)!!.
        /// </summary>
        internal static string MSG_ERROR_CXL_9 {
            get {
                return ResourceManager.GetString("MSG_ERROR_CXL_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input groom&apos;s e-mail address.
        /// </summary>
        internal static string MSG_ERROR_GROOM_EMAIL {
            get {
                return ResourceManager.GetString("MSG_ERROR_GROOM_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied in Japan! Cannot use this Coupon....
        /// </summary>
        internal static string MSG_ERROR_JAPANESE_USE {
            get {
                return ResourceManager.GetString("MSG_ERROR_JAPANESE_USE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must Input Agent Code!!.
        /// </summary>
        internal static string MSG_ERROR_MUST_INPUT_AGENT_CD {
            get {
                return ResourceManager.GetString("MSG_ERROR_MUST_INPUT_AGENT_CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must Input Avail Time!!.
        /// </summary>
        internal static string MSG_ERROR_MUST_INPUT_AVAIL_TIME {
            get {
                return ResourceManager.GetString("MSG_ERROR_MUST_INPUT_AVAIL_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must Input Coupon Code!!.
        /// </summary>
        internal static string MSG_ERROR_MUST_INPUT_COUPON_CD {
            get {
                return ResourceManager.GetString("MSG_ERROR_MUST_INPUT_COUPON_CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must Enter CXL Date!!.
        /// </summary>
        internal static string MSG_ERROR_MUST_INPUT_CXL_DATE {
            get {
                return ResourceManager.GetString("MSG_ERROR_MUST_INPUT_CXL_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must Input Jpn Reserv Number!!.
        /// </summary>
        internal static string MSG_ERROR_MUST_INPUT_JPN_RESERV_NUMBER {
            get {
                return ResourceManager.GetString("MSG_ERROR_MUST_INPUT_JPN_RESERV_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must Input Order Date!!.
        /// </summary>
        internal static string MSG_ERROR_MUST_INPUT_ORDER_DATE {
            get {
                return ResourceManager.GetString("MSG_ERROR_MUST_INPUT_ORDER_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUST INPUT Price!!.
        /// </summary>
        internal static string MSG_ERROR_MUST_INPUT_PRICE {
            get {
                return ResourceManager.GetString("MSG_ERROR_MUST_INPUT_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUST INPUT Reason!!.
        /// </summary>
        internal static string MSG_ERROR_MUST_INPUT_REASON {
            get {
                return ResourceManager.GetString("MSG_ERROR_MUST_INPUT_REASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must Input at least One Request!!.
        /// </summary>
        internal static string MSG_ERROR_MUST_INPUT_REQUEST {
            get {
                return ResourceManager.GetString("MSG_ERROR_MUST_INPUT_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must Input Request date!!.
        /// </summary>
        internal static string MSG_ERROR_MUST_INPUT_REQUEST_DATE {
            get {
                return ResourceManager.GetString("MSG_ERROR_MUST_INPUT_REQUEST_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUST INPUT Valid Price!!.
        /// </summary>
        internal static string MSG_ERROR_MUST_INPUT_VALID_PRICE {
            get {
                return ResourceManager.GetString("MSG_ERROR_MUST_INPUT_VALID_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Records Found....
        /// </summary>
        internal static string MSG_ERROR_NORECORDS_FOUND {
            get {
                return ResourceManager.GetString("MSG_ERROR_NORECORDS_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured!  Please contact System Administrator....
        /// </summary>
        internal static string MSG_ERROR_SYSTEM_ADMINISTRATOR {
            get {
                return ResourceManager.GetString("MSG_ERROR_SYSTEM_ADMINISTRATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error..
        /// </summary>
        internal static string MSG_ERROR_UNKNOWN {
            get {
                return ResourceManager.GetString("MSG_ERROR_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Code not match with the Block assigned Agent.  Recall and Try Again....
        /// </summary>
        internal static string MSG_ERROR_UPDWEDORDER_AGENT {
            get {
                return ResourceManager.GetString("MSG_ERROR_UPDWEDORDER_AGENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already booked by someone else!!.
        /// </summary>
        internal static string MSG_ERROR_UPDWEDORDER_BOOKED {
            get {
                return ResourceManager.GetString("MSG_ERROR_UPDWEDORDER_BOOKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Church is Closed!!.  Recall and Try Again....
        /// </summary>
        internal static string MSG_ERROR_UPDWEDORDER_CLOSE {
            get {
                return ResourceManager.GetString("MSG_ERROR_UPDWEDORDER_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon Applied Items are CLEARED. Please Check....
        /// </summary>
        internal static string MSG_ERROR_UPDWEDORDER_COUPON {
            get {
                return ResourceManager.GetString("MSG_ERROR_UPDWEDORDER_COUPON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PKG is Discon!!.  Please Check....
        /// </summary>
        internal static string MSG_ERROR_UPDWEDORDER_DISCON {
            get {
                return ResourceManager.GetString("MSG_ERROR_UPDWEDORDER_DISCON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a Dedicated Time Block for Special Package....
        /// </summary>
        internal static string MSG_ERROR_UPDWEDORDER_LOCKED {
            get {
                return ResourceManager.GetString("MSG_ERROR_UPDWEDORDER_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is NON-WATABE-CONTROL Block. Please check....
        /// </summary>
        internal static string MSG_ERROR_UPDWEDORDER_NONE {
            get {
                return ResourceManager.GetString("MSG_ERROR_UPDWEDORDER_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reception Party Room is NOT Available for this time....
        /// </summary>
        internal static string MSG_ERROR_UPDWEDORDER_NORCP {
            get {
                return ResourceManager.GetString("MSG_ERROR_UPDWEDORDER_NORCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Date must be within 1-YEAR ADVANCE from today!! Please Check....
        /// </summary>
        internal static string MSG_ERROR_UPDWEDORDER_OVER {
            get {
                return ResourceManager.GetString("MSG_ERROR_UPDWEDORDER_OVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Date must be within 18-MONTH ADVANCE from today!! Please Check....
        /// </summary>
        internal static string MSG_ERROR_UPDWEDORDER_OVER18 {
            get {
                return ResourceManager.GetString("MSG_ERROR_UPDWEDORDER_OVER18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Date is EARLIER than 1-MONTH before today!! Please Check....
        /// </summary>
        internal static string MSG_ERROR_UPDWEDORDER_PAST {
            get {
                return ResourceManager.GetString("MSG_ERROR_UPDWEDORDER_PAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Church Block Info is not Exists!!  Check Master and Try Again....
        /// </summary>
        internal static string MSG_ERROR_UPDWEDORDER_RECORD {
            get {
                return ResourceManager.GetString("MSG_ERROR_UPDWEDORDER_RECORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tentavelly OK with Condition. Please confirm RCP Status....
        /// </summary>
        internal static string MSG_ERROR_UPDWEDORDER_TENTATIVE {
            get {
                return ResourceManager.GetString("MSG_ERROR_UPDWEDORDER_TENTATIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Time Range Setting OR Req.Time is not in Time Range.Check Master and Try Again....
        /// </summary>
        internal static string MSG_ERROR_UPDWEDORDER_TIME {
            get {
                return ResourceManager.GetString("MSG_ERROR_UPDWEDORDER_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Check Reception Available time for this Package....
        /// </summary>
        internal static string MSG_ERROR_UPDWEDORDER_UNMATCH {
            get {
                return ResourceManager.GetString("MSG_ERROR_UPDWEDORDER_UNMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was deleted successfully..
        /// </summary>
        internal static string MSG_FMT_DELETED {
            get {
                return ResourceManager.GetString("MSG_FMT_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer CXLD successfully..
        /// </summary>
        internal static string MSG_OK_CXLD_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("MSG_OK_CXLD_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Updated.
        /// </summary>
        internal static string MSG_OK_DATA_UPDATED {
            get {
                return ResourceManager.GetString("MSG_OK_DATA_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data was deleted successfully..
        /// </summary>
        internal static string MSG_OK_DELETED {
            get {
                return ResourceManager.GetString("MSG_OK_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My page sending is now OK..
        /// </summary>
        internal static string MSG_OK_MYPAGE_SENDING {
            get {
                return ResourceManager.GetString("MSG_OK_MYPAGE_SENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data saved successfully..
        /// </summary>
        internal static string MSG_OK_SAVED {
            get {
                return ResourceManager.GetString("MSG_OK_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey sending is now OK..
        /// </summary>
        internal static string MSG_OK_SURVEY_SENDING {
            get {
                return ResourceManager.GetString("MSG_OK_SURVEY_SENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must include at least 2 alphabetic characters, which also must include both upper case and lower case..
        /// </summary>
        internal static string MSG_PWDCHG_ALPHABETCHARERR {
            get {
                return ResourceManager.GetString("MSG_PWDCHG_ALPHABETCHARERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password is required..
        /// </summary>
        internal static string MSG_PWDCHG_CURPWDBLANKERR {
            get {
                return ResourceManager.GetString("MSG_PWDCHG_CURPWDBLANKERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password contains one or more invalid characters. (&quot;&apos;\;).
        /// </summary>
        internal static string MSG_PWDCHG_INVALIDCHARERR {
            get {
                return ResourceManager.GetString("MSG_PWDCHG_INVALIDCHARERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password is invalid..
        /// </summary>
        internal static string MSG_PWDCHG_INVALIDOLDPASS {
            get {
                return ResourceManager.GetString("MSG_PWDCHG_INVALIDOLDPASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of the new password must be between {0} to {1}..
        /// </summary>
        internal static string MSG_PWDCHG_LENGTHERR {
            get {
                return ResourceManager.GetString("MSG_PWDCHG_LENGTHERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New passwords don&apos;t match. .
        /// </summary>
        internal static string MSG_PWDCHG_NEWCONF {
            get {
                return ResourceManager.GetString("MSG_PWDCHG_NEWCONF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password is required..
        /// </summary>
        internal static string MSG_PWDCHG_NEWPWDBLANKERR {
            get {
                return ResourceManager.GetString("MSG_PWDCHG_NEWPWDBLANKERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password must be different from the current one..
        /// </summary>
        internal static string MSG_PWDCHG_NOCHANGEERR {
            get {
                return ResourceManager.GetString("MSG_PWDCHG_NOCHANGEERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must include at least one numeric character..
        /// </summary>
        internal static string MSG_PWDCHG_NUMERICCHARERR {
            get {
                return ResourceManager.GetString("MSG_PWDCHG_NUMERICCHARERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot contain more than 3 identical letters in a row. (e.g. 111, AAA, $$$).
        /// </summary>
        internal static string MSG_PWDCHG_REPEATEDERR {
            get {
                return ResourceManager.GetString("MSG_PWDCHG_REPEATEDERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be same as, or contain the user ID..
        /// </summary>
        internal static string MSG_PWDCHG_SAMEASUIDERR {
            get {
                return ResourceManager.GetString("MSG_PWDCHG_SAMEASUIDERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot contain more than 3 sequential numbers or alphabets, such as Az123, X432y, or 95ABC..
        /// </summary>
        internal static string MSG_PWDCHG_SEQUENTIALERR {
            get {
                return ResourceManager.GetString("MSG_PWDCHG_SEQUENTIALERR", resourceCulture);
            }
        }
    }
}
